version: '3.4'

services:
  Minerva.Api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - nt_Minerva
    container_name: Minerva_api
    
  Minerva.Consumer:
    environment:
      - DOTNET_ENVIRONMENT=Docker
    restart: always  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - nt_Minerva
    container_name: Minerva_consumer
    
networks:
  nt_Minerva:
    name: nt_Minerva