version: '3.4'

services:
  # Kafka Broker
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    ports:
      - "9093:9093"  # Kafka port
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_EXTERNAL: OUTSIDE
      KAFKA_ADVERTISED_LISTENER: OUTSIDE://localhost:9093
      KAFKA_LISTENERS_EXTERNAL: OUTSIDE://0.0.0.0:9093
    depends_on:
      - zookeeper

  # Zookeeper (Required by Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"  # Zookeeper port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Minerva API (Adjust as needed)
  Franz.api:
    image: ${DOCKER_REGISTRY-}minervaapi
    build:
      context: sources/back/Franz.Api/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      KAFKA_HOST: kafka  # Point to the Kafka service in Docker Compose

  # Minerva Consumer (Adjust to interact with Kafka)
  Franz.consumer:
    image: ${DOCKER_REGISTRY-}Franzconsumer
    build:
      context: sources/back/Franz.Consumer/
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: kafka:9093  # Kafka broker address (use service name and port)
      KAFKA_GROUP_ID: consumer-group
      KAFKA_TOPIC: your_topic_name  # Adjust this to your Kafka topic
    depends_on:
      - kafka  # Ensure Kafka is available before starting the consumer


